### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by senllh** [RuijiaW/Multi-Component-Graph-Convolutional-Collaborative-Filtering#1]
Excuse me, when will you show the code？

**Comment by RuijiaW** [comment]
THANKS for your attention to our work :) My apologies for the empty repo on GitHub. Recently I'm busy with another work, so haven't spared time for organizing code yet. The code will be available in early March. After that, we look forward to having further discussions with you!

**Comment by RuijiaW** [comment]
> Excuse me, when will you show the code？

THANKS for your attention to our work :) My apologies for the empty repo on GitHub. Recently I'm busy with another work, so haven't spared time for organizing code yet. The code will be available in early March. After that, we look forward to having further discussions with you!

**Comment by senllh** [comment]
Thanks for your reply. I am interested in your research and look forward to your code shown.
